version: 2.1

commands:
  print_id:
    description: "print_pipeline_id"
    parameters: 
      id: 
        type: string
    steps:
      - run: echo << parameters.id >>

jobs:
  my_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_id:
          id: << pipeline.id >>

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello world $Author > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - my_command
      - print_output_file:
          requires:
            - save_hello_world_output
