version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo Hello, World! from $Author

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
